///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompanyDetailDataLanguagesNumbers {
/*
{
  "user_id": 14,
  "language": "Arabic (DZ)",
  "country_code": "US",
  "phone_code": "+1",
  "phone_number": "3333398556"
}
*/

  int? userId;
  String? language;
  String? countryCode;
  String? phoneCode;
  String? phoneNumber;

  CompanyDetailDataLanguagesNumbers({
    this.userId,
    this.language,
    this.countryCode,
    this.phoneCode,
    this.phoneNumber,
  });
  CompanyDetailDataLanguagesNumbers.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    language = json['language']?.toString();
    countryCode = json['country_code']?.toString();
    phoneCode = json['phone_code']?.toString();
    phoneNumber = json['phone_number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['language'] = language;
    data['country_code'] = countryCode;
    data['phone_code'] = phoneCode;
    data['phone_number'] = phoneNumber;
    return data;
  }
}

class CompanyDetailDataLanguages {
/*
{
  "language_name": "Arabic (DZ)",
  "numbers": [
    {
      "user_id": 14,
      "language": "Arabic (DZ)",
      "country_code": "US",
      "phone_code": "+1",
      "phone_number": "3333398556"
    }
  ]
}
*/

  String? languageName;
  List<CompanyDetailDataLanguagesNumbers?>? numbers;

  CompanyDetailDataLanguages({
    this.languageName,
    this.numbers,
  });
  CompanyDetailDataLanguages.fromJson(Map<String, dynamic> json) {
    languageName = json['language_name']?.toString();
    if (json['numbers'] != null) {
      final v = json['numbers'];
      final arr0 = <CompanyDetailDataLanguagesNumbers>[];
      v.forEach((v) {
        arr0.add(CompanyDetailDataLanguagesNumbers.fromJson(v));
      });
      numbers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language_name'] = languageName;
    if (numbers != null) {
      final v = numbers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['numbers'] = arr0;
    }
    return data;
  }
}

class CompanyDetailData {
/*
{
  "id": 14,
  "otp": null,
  "role": "business",
  "full_name": "Business",
  "email": "business@getnada.com",
  "phone_number": "3664546984",
  "phone_code": "+1",
  "country_code": "US",
  "address": "U.S. Bank Stadium, Chicago Avenue, Minneapolis, MN, USA",
  "website": "www",
  "profile_image": null,
  "company_name": "Business",
  "company_description": "description is here",
  "card_id": null,
  "is_card": 0,
  "customer_id": null,
  "account_verified": 1,
  "email_verified_at": "2023-11-08T05:34:48.000000Z",
  "device_type": null,
  "device_token": null,
  "is_social": 0,
  "is_forgot": 0,
  "user_social_token": null,
  "user_social_type": null,
  "is_profile_complete": 1,
  "is_blocked": 0,
  "subscription_id": 1,
  "api_token": "26|NS30L0MvkFWoouLTSLWc8t3qGbtCjUyEVQxNPr6I17302c37",
  "notifications": 1,
  "deleted_at": null,
  "created_at": "2023-11-08T05:34:43.000000Z",
  "updated_at": "2023-11-08T09:34:00.000000Z",
  "is_favorite_count": 0,
  "average_rating": null,
  "languages": [
    {
      "language_name": "Arabic (DZ)",
      "numbers": [
        {
          "user_id": 14,
          "language": "Arabic (DZ)",
          "country_code": "US",
          "phone_code": "+1",
          "phone_number": "3333398556"
        }
      ]
    }
  ]
}
*/

  int? id;
  String? otp;
  String? role;
  String? fullName;
  String? email;
  String? phoneNumber;
  String? phoneCode;
  String? countryCode;
  String? address;
  String? website;
  String? profileImage;
  String? companyName;
  String? companyDescription;
  String? cardId;
  int? isCard;
  String? customerId;
  int? accountVerified;
  String? emailVerifiedAt;
  String? deviceType;
  String? deviceToken;
  int? isSocial;
  int? isForgot;
  String? userSocialToken;
  String? userSocialType;
  int? isProfileComplete;
  int? isBlocked;
  int? subscriptionId;
  String? apiToken;
  int? notifications;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  int? isFavoriteCount;
  String? averageRating;
  List<CompanyDetailDataLanguages?>? languages;

  CompanyDetailData({
    this.id,
    this.otp,
    this.role,
    this.fullName,
    this.email,
    this.phoneNumber,
    this.phoneCode,
    this.countryCode,
    this.address,
    this.website,
    this.profileImage,
    this.companyName,
    this.companyDescription,
    this.cardId,
    this.isCard,
    this.customerId,
    this.accountVerified,
    this.emailVerifiedAt,
    this.deviceType,
    this.deviceToken,
    this.isSocial,
    this.isForgot,
    this.userSocialToken,
    this.userSocialType,
    this.isProfileComplete,
    this.isBlocked,
    this.subscriptionId,
    this.apiToken,
    this.notifications,
    this.deletedAt,
    this.createdAt,
    this.updatedAt,
    this.isFavoriteCount,
    this.averageRating,
    this.languages,
  });
  CompanyDetailData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    otp = json['otp']?.toString();
    role = json['role']?.toString();
    fullName = json['full_name']?.toString();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneCode = json['phone_code']?.toString();
    countryCode = json['country_code']?.toString();
    address = json['address']?.toString();
    website = json['website']?.toString();
    profileImage = json['profile_image']?.toString();
    companyName = json['company_name']?.toString();
    companyDescription = json['company_description']?.toString();
    cardId = json['card_id']?.toString();
    isCard = json['is_card']?.toInt();
    customerId = json['customer_id']?.toString();
    accountVerified = json['account_verified']?.toInt();
    emailVerifiedAt = json['email_verified_at']?.toString();
    deviceType = json['device_type']?.toString();
    deviceToken = json['device_token']?.toString();
    isSocial = json['is_social']?.toInt();
    isForgot = json['is_forgot']?.toInt();
    userSocialToken = json['user_social_token']?.toString();
    userSocialType = json['user_social_type']?.toString();
    isProfileComplete = json['is_profile_complete']?.toInt();
    isBlocked = json['is_blocked']?.toInt();
    subscriptionId = json['subscription_id']?.toInt();
    apiToken = json['api_token']?.toString();
    notifications = json['notifications']?.toInt();
    deletedAt = json['deleted_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    isFavoriteCount = json['is_favorite_count']?.toInt();
    averageRating = json['average_rating']?.toString();
    if (json['languages'] != null) {
      final v = json['languages'];
      final arr0 = <CompanyDetailDataLanguages>[];
      v.forEach((v) {
        arr0.add(CompanyDetailDataLanguages.fromJson(v));
      });
      languages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['otp'] = otp;
    data['role'] = role;
    data['full_name'] = fullName;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_code'] = phoneCode;
    data['country_code'] = countryCode;
    data['address'] = address;
    data['website'] = website;
    data['profile_image'] = profileImage;
    data['company_name'] = companyName;
    data['company_description'] = companyDescription;
    data['card_id'] = cardId;
    data['is_card'] = isCard;
    data['customer_id'] = customerId;
    data['account_verified'] = accountVerified;
    data['email_verified_at'] = emailVerifiedAt;
    data['device_type'] = deviceType;
    data['device_token'] = deviceToken;
    data['is_social'] = isSocial;
    data['is_forgot'] = isForgot;
    data['user_social_token'] = userSocialToken;
    data['user_social_type'] = userSocialType;
    data['is_profile_complete'] = isProfileComplete;
    data['is_blocked'] = isBlocked;
    data['subscription_id'] = subscriptionId;
    data['api_token'] = apiToken;
    data['notifications'] = notifications;
    data['deleted_at'] = deletedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['is_favorite_count'] = isFavoriteCount;
    data['average_rating'] = averageRating;
    if (languages != null) {
      final v = languages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['languages'] = arr0;
    }
    return data;
  }
}

class CompanyDetail {
/*
{
  "status": 1,
  "message": "Company Details",
  "data": {
    "id": 14,
    "otp": null,
    "role": "business",
    "full_name": "Business",
    "email": "business@getnada.com",
    "phone_number": "3664546984",
    "phone_code": "+1",
    "country_code": "US",
    "address": "U.S. Bank Stadium, Chicago Avenue, Minneapolis, MN, USA",
    "website": "www",
    "profile_image": null,
    "company_name": "Business",
    "company_description": "description is here",
    "card_id": null,
    "is_card": 0,
    "customer_id": null,
    "account_verified": 1,
    "email_verified_at": "2023-11-08T05:34:48.000000Z",
    "device_type": null,
    "device_token": null,
    "is_social": 0,
    "is_forgot": 0,
    "user_social_token": null,
    "user_social_type": null,
    "is_profile_complete": 1,
    "is_blocked": 0,
    "subscription_id": 1,
    "api_token": "26|NS30L0MvkFWoouLTSLWc8t3qGbtCjUyEVQxNPr6I17302c37",
    "notifications": 1,
    "deleted_at": null,
    "created_at": "2023-11-08T05:34:43.000000Z",
    "updated_at": "2023-11-08T09:34:00.000000Z",
    "is_favorite_count": 0,
    "average_rating": null,
    "languages": [
      {
        "language_name": "Arabic (DZ)",
        "numbers": [
          {
            "user_id": 14,
            "language": "Arabic (DZ)",
            "country_code": "US",
            "phone_code": "+1",
            "phone_number": "3333398556"
          }
        ]
      }
    ]
  }
}
*/

  int? status;
  String? message;
  CompanyDetailData? data;

  CompanyDetail({
    this.status,
    this.message,
    this.data,
  });
  CompanyDetail.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? CompanyDetailData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}


// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class CompanyDetailData {
// /*
// {
//   "id": 12,
//   "otp": null,
//   "role": "business",
//   "full_name": "Demo User",
//   "email": "business@gmail.com",
//   "phone_number": "2222434556",
//   "phone_code": null,
//   "country_code": null,
//   "address": null,
//   "website": null,
//   "profile_image": "profile_image/9BsyJ4EhvGUzeWSu5oVdUurUyWOTAZetFwhfYZq3.png",
//   "company_name": "AAD",
//   "company_description": "company_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_description",
//   "card_id": null,
//   "is_card": 0,
//   "customer_id": null,
//   "account_verified": 1,
//   "email_verified_at": "2023-10-17T11:10:08.000000Z",
//   "device_type": null,
//   "device_token": null,
//   "is_social": 0,
//   "is_forgot": 0,
//   "user_social_token": null,
//   "user_social_type": null,
//   "is_profile_complete": 1,
//   "is_blocked": 0,
//   "subscription_id": 1,
//   "api_token": "57|D3IFk2LNeDuxfZoXRutCGjzIBlL8lNPFNrlsuUWe39c0a02d",
//   "notifications": 0,
//   "deleted_at": null,
//   "created_at": "2023-10-17T11:09:47.000000Z",
//   "updated_at": "2023-10-31T11:00:13.000000Z",
//   "average_rating": 4.25
// }
// */
//
//   int? id;
//   String? otp;
//   String? role;
//   String? fullName;
//   String? email;
//   String? phoneNumber;
//   String? phoneCode;
//   String? countryCode;
//   String? address;
//   String? website;
//   String? profileImage;
//   String? companyName;
//   String? companyDescription;
//   String? cardId;
//   int? isCard;
//   String? customerId;
//   int? accountVerified;
//   String? emailVerifiedAt;
//   String? deviceType;
//   String? deviceToken;
//   int? isSocial;
//   int? isForgot;
//   String? userSocialToken;
//   String? userSocialType;
//   int? isProfileComplete;
//   int? isBlocked;
//   int? subscriptionId;
//   String? apiToken;
//   int? notifications;
//   String? deletedAt;
//   String? createdAt;
//   String? updatedAt;
//   int? isFavoriteCount;
//   double? averageRating;
//
//   CompanyDetailData({
//     this.id,
//     this.otp,
//     this.role,
//     this.fullName,
//     this.email,
//     this.phoneNumber,
//     this.phoneCode,
//     this.countryCode,
//     this.address,
//     this.website,
//     this.profileImage,
//     this.companyName,
//     this.companyDescription,
//     this.cardId,
//     this.isCard,
//     this.customerId,
//     this.accountVerified,
//     this.emailVerifiedAt,
//     this.deviceType,
//     this.deviceToken,
//     this.isSocial,
//     this.isForgot,
//     this.userSocialToken,
//     this.userSocialType,
//     this.isProfileComplete,
//     this.isBlocked,
//     this.subscriptionId,
//     this.apiToken,
//     this.notifications,
//     this.deletedAt,
//     this.createdAt,
//     this.updatedAt,
//     this.isFavoriteCount,
//     this.averageRating,
//   });
//   CompanyDetailData.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     otp = json['otp']?.toString();
//     role = json['role']?.toString();
//     fullName = json['full_name']?.toString();
//     email = json['email']?.toString();
//     phoneNumber = json['phone_number']?.toString();
//     phoneCode = json['phone_code']?.toString();
//     countryCode = json['country_code']?.toString();
//     address = json['address']?.toString();
//     website = json['website']?.toString();
//     profileImage = json['profile_image']?.toString();
//     companyName = json['company_name']?.toString();
//     companyDescription = json['company_description']?.toString();
//     cardId = json['card_id']?.toString();
//     isCard = json['is_card']?.toInt();
//     customerId = json['customer_id']?.toString();
//     accountVerified = json['account_verified']?.toInt();
//     emailVerifiedAt = json['email_verified_at']?.toString();
//     deviceType = json['device_type']?.toString();
//     deviceToken = json['device_token']?.toString();
//     isSocial = json['is_social']?.toInt();
//     isForgot = json['is_forgot']?.toInt();
//     userSocialToken = json['user_social_token']?.toString();
//     userSocialType = json['user_social_type']?.toString();
//     isProfileComplete = json['is_profile_complete']?.toInt();
//     isBlocked = json['is_blocked']?.toInt();
//     subscriptionId = json['subscription_id']?.toInt();
//     apiToken = json['api_token']?.toString();
//     notifications = json['notifications']?.toInt();
//     deletedAt = json['deleted_at']?.toString();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     isFavoriteCount = json['is_favorite_count']?.toInt();
//     averageRating = json['average_rating']?.toDouble();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['otp'] = otp;
//     data['role'] = role;
//     data['full_name'] = fullName;
//     data['email'] = email;
//     data['phone_number'] = phoneNumber;
//     data['phone_code'] = phoneCode;
//     data['country_code'] = countryCode;
//     data['address'] = address;
//     data['website'] = website;
//     data['profile_image'] = profileImage;
//     data['company_name'] = companyName;
//     data['company_description'] = companyDescription;
//     data['card_id'] = cardId;
//     data['is_card'] = isCard;
//     data['customer_id'] = customerId;
//     data['account_verified'] = accountVerified;
//     data['email_verified_at'] = emailVerifiedAt;
//     data['device_type'] = deviceType;
//     data['device_token'] = deviceToken;
//     data['is_social'] = isSocial;
//     data['is_forgot'] = isForgot;
//     data['user_social_token'] = userSocialToken;
//     data['user_social_type'] = userSocialType;
//     data['is_profile_complete'] = isProfileComplete;
//     data['is_blocked'] = isBlocked;
//     data['subscription_id'] = subscriptionId;
//     data['api_token'] = apiToken;
//     data['notifications'] = notifications;
//     data['deleted_at'] = deletedAt;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['is_favorite_count'] = isFavoriteCount;
//     data['average_rating'] = averageRating;
//     return data;
//   }
// }
//
// class CompanyDetail {
// /*
// {
//   "status": 1,
//   "message": "Company Details",
//   "data": {
//     "id": 12,
//     "otp": null,
//     "role": "business",
//     "full_name": "Demo User",
//     "email": "business@gmail.com",
//     "phone_number": "2222434556",
//     "phone_code": null,
//     "country_code": null,
//     "address": null,
//     "website": null,
//     "profile_image": "profile_image/9BsyJ4EhvGUzeWSu5oVdUurUyWOTAZetFwhfYZq3.png",
//     "company_name": "AAD",
//     "company_description": "company_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_description",
//     "card_id": null,
//     "is_card": 0,
//     "customer_id": null,
//     "account_verified": 1,
//     "email_verified_at": "2023-10-17T11:10:08.000000Z",
//     "device_type": null,
//     "device_token": null,
//     "is_social": 0,
//     "is_forgot": 0,
//     "user_social_token": null,
//     "user_social_type": null,
//     "is_profile_complete": 1,
//     "is_blocked": 0,
//     "subscription_id": 1,
//     "api_token": "57|D3IFk2LNeDuxfZoXRutCGjzIBlL8lNPFNrlsuUWe39c0a02d",
//     "notifications": 0,
//     "deleted_at": null,
//     "created_at": "2023-10-17T11:09:47.000000Z",
//     "updated_at": "2023-10-31T11:00:13.000000Z",
//     "average_rating": 4.25
//   }
// }
// */
//
//   int? status;
//   String? message;
//   CompanyDetailData? data;
//
//   CompanyDetail({
//     this.status,
//     this.message,
//     this.data,
//   });
//   CompanyDetail.fromJson(Map<String, dynamic> json) {
//     status = json['status']?.toInt();
//     message = json['message']?.toString();
//     data = (json['data'] != null) ? CompanyDetailData.fromJson(json['data']) : null;
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['status'] = status;
//     data['message'] = message;
//     if (data != null) {
//       data['data'] = this.data!.toJson();
//     }
//     return data;
//   }
// }
//
//
// // ///
// // /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// // ///
// // class CompanyDetailData {
// // /*
// // {
// //   "id": 12,
// //   "otp": null,
// //   "role": "business",
// //   "full_name": "Demo User",
// //   "email": "business@gmail.com",
// //   "phone_number": "2222434556",
// //   "phone_code": null,
// //   "country_code": null,
// //   "address": null,
// //   "website": null,
// //   "profile_image": "profile_image/9BsyJ4EhvGUzeWSu5oVdUurUyWOTAZetFwhfYZq3.png",
// //   "company_name": null,
// //   "company_description": "company_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_description",
// //   "card_id": null,
// //   "is_card": 0,
// //   "customer_id": null,
// //   "account_verified": 1,
// //   "email_verified_at": "2023-10-17T11:10:08.000000Z",
// //   "device_type": "android",
// //   "device_token": "123",
// //   "is_social": 0,
// //   "is_forgot": 0,
// //   "user_social_token": null,
// //   "user_social_type": null,
// //   "is_profile_complete": 1,
// //   "is_blocked": 0,
// //   "subscription_id": null,
// //   "api_token": "57|D3IFk2LNeDuxfZoXRutCGjzIBlL8lNPFNrlsuUWe39c0a02d",
// //   "notifications": 1,
// //   "deleted_at": null,
// //   "created_at": "2023-10-17T11:09:47.000000Z",
// //   "updated_at": "2023-10-30T06:24:38.000000Z"
// // }
// // */
// //
// //   int? id;
// //   String? otp;
// //   String? role;
// //   String? fullName;
// //   String? email;
// //   String? phoneNumber;
// //   String? phoneCode;
// //   String? countryCode;
// //   String? address;
// //   String? website;
// //   String? profileImage;
// //   String? companyName;
// //   String? companyDescription;
// //   String? cardId;
// //   int? isCard;
// //   String? customerId;
// //   int? accountVerified;
// //   String? emailVerifiedAt;
// //   String? deviceType;
// //   String? deviceToken;
// //   int? isSocial;
// //   int? isForgot;
// //   String? userSocialToken;
// //   String? userSocialType;
// //   int? isProfileComplete;
// //   int? isBlocked;
// //   String? subscriptionId;
// //   String? apiToken;
// //   int? notifications;
// //   String? deletedAt;
// //   String? createdAt;
// //   String? updatedAt;
// //
// //   CompanyDetailData({
// //     this.id,
// //     this.otp,
// //     this.role,
// //     this.fullName,
// //     this.email,
// //     this.phoneNumber,
// //     this.phoneCode,
// //     this.countryCode,
// //     this.address,
// //     this.website,
// //     this.profileImage,
// //     this.companyName,
// //     this.companyDescription,
// //     this.cardId,
// //     this.isCard,
// //     this.customerId,
// //     this.accountVerified,
// //     this.emailVerifiedAt,
// //     this.deviceType,
// //     this.deviceToken,
// //     this.isSocial,
// //     this.isForgot,
// //     this.userSocialToken,
// //     this.userSocialType,
// //     this.isProfileComplete,
// //     this.isBlocked,
// //     this.subscriptionId,
// //     this.apiToken,
// //     this.notifications,
// //     this.deletedAt,
// //     this.createdAt,
// //     this.updatedAt,
// //   });
// //   CompanyDetailData.fromJson(Map<String, dynamic> json) {
// //     id = json['id']?.toInt();
// //     otp = json['otp']?.toString();
// //     role = json['role']?.toString();
// //     fullName = json['full_name']?.toString();
// //     email = json['email']?.toString();
// //     phoneNumber = json['phone_number']?.toString();
// //     phoneCode = json['phone_code']?.toString();
// //     countryCode = json['country_code']?.toString();
// //     address = json['address']?.toString();
// //     website = json['website']?.toString();
// //     profileImage = json['profile_image']?.toString();
// //     companyName = json['company_name']?.toString();
// //     companyDescription = json['company_description']?.toString();
// //     cardId = json['card_id']?.toString();
// //     isCard = json['is_card']?.toInt();
// //     customerId = json['customer_id']?.toString();
// //     accountVerified = json['account_verified']?.toInt();
// //     emailVerifiedAt = json['email_verified_at']?.toString();
// //     deviceType = json['device_type']?.toString();
// //     deviceToken = json['device_token']?.toString();
// //     isSocial = json['is_social']?.toInt();
// //     isForgot = json['is_forgot']?.toInt();
// //     userSocialToken = json['user_social_token']?.toString();
// //     userSocialType = json['user_social_type']?.toString();
// //     isProfileComplete = json['is_profile_complete']?.toInt();
// //     isBlocked = json['is_blocked']?.toInt();
// //     subscriptionId = json['subscription_id']?.toString();
// //     apiToken = json['api_token']?.toString();
// //     notifications = json['notifications']?.toInt();
// //     deletedAt = json['deleted_at']?.toString();
// //     createdAt = json['created_at']?.toString();
// //     updatedAt = json['updated_at']?.toString();
// //   }
// //   Map<String, dynamic> toJson() {
// //     final data = <String, dynamic>{};
// //     data['id'] = id;
// //     data['otp'] = otp;
// //     data['role'] = role;
// //     data['full_name'] = fullName;
// //     data['email'] = email;
// //     data['phone_number'] = phoneNumber;
// //     data['phone_code'] = phoneCode;
// //     data['country_code'] = countryCode;
// //     data['address'] = address;
// //     data['website'] = website;
// //     data['profile_image'] = profileImage;
// //     data['company_name'] = companyName;
// //     data['company_description'] = companyDescription;
// //     data['card_id'] = cardId;
// //     data['is_card'] = isCard;
// //     data['customer_id'] = customerId;
// //     data['account_verified'] = accountVerified;
// //     data['email_verified_at'] = emailVerifiedAt;
// //     data['device_type'] = deviceType;
// //     data['device_token'] = deviceToken;
// //     data['is_social'] = isSocial;
// //     data['is_forgot'] = isForgot;
// //     data['user_social_token'] = userSocialToken;
// //     data['user_social_type'] = userSocialType;
// //     data['is_profile_complete'] = isProfileComplete;
// //     data['is_blocked'] = isBlocked;
// //     data['subscription_id'] = subscriptionId;
// //     data['api_token'] = apiToken;
// //     data['notifications'] = notifications;
// //     data['deleted_at'] = deletedAt;
// //     data['created_at'] = createdAt;
// //     data['updated_at'] = updatedAt;
// //     return data;
// //   }
// // }
// //
// // class CompanyDetail {
// // /*
// // {
// //   "status": 1,
// //   "message": "Company Details",
// //   "data": {
// //     "id": 12,
// //     "otp": null,
// //     "role": "business",
// //     "full_name": "Demo User",
// //     "email": "business@gmail.com",
// //     "phone_number": "2222434556",
// //     "phone_code": null,
// //     "country_code": null,
// //     "address": null,
// //     "website": null,
// //     "profile_image": "profile_image/9BsyJ4EhvGUzeWSu5oVdUurUyWOTAZetFwhfYZq3.png",
// //     "company_name": null,
// //     "company_description": "company_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_descriptioncompany_description",
// //     "card_id": null,
// //     "is_card": 0,
// //     "customer_id": null,
// //     "account_verified": 1,
// //     "email_verified_at": "2023-10-17T11:10:08.000000Z",
// //     "device_type": "android",
// //     "device_token": "123",
// //     "is_social": 0,
// //     "is_forgot": 0,
// //     "user_social_token": null,
// //     "user_social_type": null,
// //     "is_profile_complete": 1,
// //     "is_blocked": 0,
// //     "subscription_id": null,
// //     "api_token": "57|D3IFk2LNeDuxfZoXRutCGjzIBlL8lNPFNrlsuUWe39c0a02d",
// //     "notifications": 1,
// //     "deleted_at": null,
// //     "created_at": "2023-10-17T11:09:47.000000Z",
// //     "updated_at": "2023-10-30T06:24:38.000000Z"
// //   }
// // }
// // */
// //
// //   int? status;
// //   String? message;
// //   CompanyDetailData? data;
// //
// //   CompanyDetail({
// //     this.status,
// //     this.message,
// //     this.data,
// //   });
// //   CompanyDetail.fromJson(Map<String, dynamic> json) {
// //     status = json['status']?.toInt();
// //     message = json['message']?.toString();
// //     data = (json['data'] != null) ? CompanyDetailData.fromJson(json['data']) : null;
// //   }
// //   Map<String, dynamic> toJson() {
// //     final data = <String, dynamic>{};
// //     data['status'] = status;
// //     data['message'] = message;
// //     if (data != null) {
// //       data['data'] = this.data!.toJson();
// //     }
// //     return data;
// //   }
// // }
