///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReviewsModelDataUser {
/*
{
  "id": 4,
  "full_name": "Demo User",
  "profile_image": "profile_image/fzman6DHZrjPvOYBfNSf8SNRwRDHZVQagHP7xVZB.png"
}
*/

  int? id;
  String? fullName;
  String? profileImage;

  ReviewsModelDataUser({
    this.id,
    this.fullName,
    this.profileImage,
  });
  ReviewsModelDataUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fullName = json['full_name']?.toString();
    profileImage = json['profile_image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['full_name'] = fullName;
    data['profile_image'] = profileImage;
    return data;
  }
}

class ReviewsModelData {
/*
{
  "id": 2,
  "user_id": 4,
  "company_id": 12,
  "rating": 4.5,
  "feedback": "I like their services",
  "created_at": "2023-10-30T07:27:28.000000Z",
  "updated_at": "2023-10-30T07:27:28.000000Z",
  "user": {
    "id": 4,
    "full_name": "Demo User",
    "profile_image": "profile_image/fzman6DHZrjPvOYBfNSf8SNRwRDHZVQagHP7xVZB.png"
  }
}
*/

  int? id;
  int? userId;
  int? companyId;
  double? rating;
  String? feedback;
  String? createdAt;
  String? updatedAt;
  ReviewsModelDataUser? user;

  ReviewsModelData({
    this.id,
    this.userId,
    this.companyId,
    this.rating,
    this.feedback,
    this.createdAt,
    this.updatedAt,
    this.user,
  });
  ReviewsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    companyId = json['company_id']?.toInt();
    rating = json['rating']?.toDouble();
    feedback = json['feedback']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    user = (json['user'] != null) ? ReviewsModelDataUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['company_id'] = companyId;
    data['rating'] = rating;
    data['feedback'] = feedback;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class ReviewsModel {
/*
{
  "status": 1,
  "message": "Reviews",
  "data": [
    {
      "id": 2,
      "user_id": 4,
      "company_id": 12,
      "rating": 4.5,
      "feedback": "I like their services",
      "created_at": "2023-10-30T07:27:28.000000Z",
      "updated_at": "2023-10-30T07:27:28.000000Z",
      "user": {
        "id": 4,
        "full_name": "Demo User",
        "profile_image": "profile_image/fzman6DHZrjPvOYBfNSf8SNRwRDHZVQagHP7xVZB.png"
      }
    }
  ]
}
*/

  int? status;
  String? message;
  List<ReviewsModelData?>? data;

  ReviewsModel({
    this.status,
    this.message,
    this.data,
  });
  ReviewsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ReviewsModelData>[];
      v.forEach((v) {
        arr0.add(ReviewsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
