///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ServiceDetailsModelDataUser {
/*
{
  "id": 2,
  "company_name": "Demo Company",
  "profile_image": null,
  "website": "www.google.com"
}
*/

  int? id;
  String? companyName;
  String? profileImage;
  String? website;

  ServiceDetailsModelDataUser({
    this.id,
    this.companyName,
    this.profileImage,
    this.website,
  });
  ServiceDetailsModelDataUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    companyName = json['company_name']?.toString();
    profileImage = json['profile_image']?.toString();
    website = json['website']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['company_name'] = companyName;
    data['profile_image'] = profileImage;
    data['website'] = website;
    return data;
  }
}

class ServiceDetailsModelData {
/*
{
  "id": 1,
  "user_id": 2,
  "service_image": null,
  "name": "Service1dfr",
  "location": "New York, NY, USA",
  "description": "Service Description",
  "created_at": "2023-11-07T11:57:35.000000Z",
  "updated_at": "2023-11-07T11:59:53.000000Z",
  "user": {
    "id": 2,
    "company_name": "Demo Company",
    "profile_image": null,
    "website": "www.google.com"
  }
}
*/

  int? id;
  int? userId;
  String? serviceImage;
  String? name;
  String? location;
  String? description;
  String? createdAt;
  String? updatedAt;
  ServiceDetailsModelDataUser? user;

  ServiceDetailsModelData({
    this.id,
    this.userId,
    this.serviceImage,
    this.name,
    this.location,
    this.description,
    this.createdAt,
    this.updatedAt,
    this.user,
  });
  ServiceDetailsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['user_id']?.toInt();
    serviceImage = json['service_image']?.toString();
    name = json['name']?.toString();
    location = json['location']?.toString();
    description = json['description']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    user = (json['user'] != null) ? ServiceDetailsModelDataUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['service_image'] = serviceImage;
    data['name'] = name;
    data['location'] = location;
    data['description'] = description;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class ServiceDetailsModel {
/*
{
  "status": 1,
  "message": "Service Details",
  "data": {
    "id": 1,
    "user_id": 2,
    "service_image": null,
    "name": "Service1dfr",
    "location": "New York, NY, USA",
    "description": "Service Description",
    "created_at": "2023-11-07T11:57:35.000000Z",
    "updated_at": "2023-11-07T11:59:53.000000Z",
    "user": {
      "id": 2,
      "company_name": "Demo Company",
      "profile_image": null,
      "website": "www.google.com"
    }
  }
}
*/

  int? status;
  String? message;
  ServiceDetailsModelData? data;

  ServiceDetailsModel({
    this.status,
    this.message,
    this.data,
  });
  ServiceDetailsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? ServiceDetailsModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}


// class ServiceDetailsModelData {
// /*
// {
//   "id": 1,
//   "user_id": 4,
//   "service_image": "service_image/g5MyqmHPMLHwLfz1hDm36oyLqnzLTD1wg3J3bDWX.png",
//   "name": "eyr",
//   "location": "E C Stoner Building, Woodhouse, Leeds, UK",
//   "description": "v",
//   "created_at": "2023-10-24T07:48:47.000000Z",
//   "updated_at": "2023-10-25T11:47:57.000000Z"
// }
// */
//
//   int? id;
//   int? userId;
//   String? serviceImage;
//   String? name;
//   String? location;
//   String? description;
//   String? createdAt;
//   String? updatedAt;
//
//   ServiceDetailsModelData({
//     this.id,
//     this.userId,
//     this.serviceImage,
//     this.name,
//     this.location,
//     this.description,
//     this.createdAt,
//     this.updatedAt,
//   });
//   ServiceDetailsModelData.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     userId = json['user_id']?.toInt();
//     serviceImage = json['service_image']?.toString();
//     name = json['name']?.toString();
//     location = json['location']?.toString();
//     description = json['description']?.toString();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['user_id'] = userId;
//     data['service_image'] = serviceImage;
//     data['name'] = name;
//     data['location'] = location;
//     data['description'] = description;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     return data;
//   }
// }
//
// class ServiceDetailsModel {
// /*
// {
//   "status": 1,
//   "message": "Service Details",
//   "data": {
//     "id": 1,
//     "user_id": 4,
//     "service_image": "service_image/g5MyqmHPMLHwLfz1hDm36oyLqnzLTD1wg3J3bDWX.png",
//     "name": "eyr",
//     "location": "E C Stoner Building, Woodhouse, Leeds, UK",
//     "description": "v",
//     "created_at": "2023-10-24T07:48:47.000000Z",
//     "updated_at": "2023-10-25T11:47:57.000000Z"
//   }
// }
// */
//
//   int? status;
//   String? message;
//   ServiceDetailsModelData? data;
//
//   ServiceDetailsModel({
//     this.status,
//     this.message,
//     this.data,
//   });
//   ServiceDetailsModel.fromJson(Map<String, dynamic> json) {
//     status = json['status']?.toInt();
//     message = json['message']?.toString();
//     data = (json['data'] != null) ? ServiceDetailsModelData.fromJson(json['data']) : null;
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['status'] = status;
//     data['message'] = message;
//     if (data != null) {
//       data['data'] = this.data!.toJson();
//     }
//     return data;
//   }
// }
