///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChatMessagesModelData {
/*
{
  "sender_id": 24,
  "receiver_id": 4,
  "type": "text",
  "last_message": "hello",
  "created_at": "2023-11-03T09:56:53.000000Z",
  "id": 24,
  "full_name": "USER",
  "profile_image": null,
  "days": "Today"
}
*/

  int? senderId;
  int? receiverId;
  String? type;
  String? lastMessage;
  String? createdAt;
  int? id;
  String? fullName;
  String? profileImage;
  String? days;

  ChatMessagesModelData({
    this.senderId,
    this.receiverId,
    this.type,
    this.lastMessage,
    this.createdAt,
    this.id,
    this.fullName,
    this.profileImage,
    this.days,
  });
  ChatMessagesModelData.fromJson(Map<String, dynamic> json) {
    senderId = json['sender_id']?.toInt();
    receiverId = json['receiver_id']?.toInt();
    type = json['type']?.toString();
    lastMessage = json['last_message']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
    fullName = json['full_name']?.toString();
    profileImage = json['profile_image']?.toString();
    days = json['days']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['sender_id'] = senderId;
    data['receiver_id'] = receiverId;
    data['type'] = type;
    data['last_message'] = lastMessage;
    data['created_at'] = createdAt;
    data['id'] = id;
    data['full_name'] = fullName;
    data['profile_image'] = profileImage;
    data['days'] = days;
    return data;
  }
}

class ChatMessagesModel {
/*
{
  "status": 1,
  "message": "Messages",
  "data": [
    {
      "sender_id": 24,
      "receiver_id": 4,
      "type": "text",
      "last_message": "hello",
      "created_at": "2023-11-03T09:56:53.000000Z",
      "id": 24,
      "full_name": "USER",
      "profile_image": null,
      "days": "Today"
    }
  ]
}
*/

  int? status;
  String? message;
  List<ChatMessagesModelData?>? data;

  ChatMessagesModel({
    this.status,
    this.message,
    this.data,
  });
  ChatMessagesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ChatMessagesModelData>[];
      v.forEach((v) {
        arr0.add(ChatMessagesModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
