///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationsModelDataUser {
/*
{
  "id": 36,
  "full_name": "demouser11",
  "company_name": null,
  "profile_image": "profile_image/srd5iwWHMB3wTnCvICKewxve3hu4eKcqwP3kdD0I.jpg"
}
*/

  int? id;
  String? fullName;
  String? companyName;
  String? profileImage;

  NotificationsModelDataUser({
    this.id,
    this.fullName,
    this.companyName,
    this.profileImage,
  });
  NotificationsModelDataUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    fullName = json['full_name']?.toString();
    companyName = json['company_name']?.toString();
    profileImage = json['profile_image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['full_name'] = fullName;
    data['company_name'] = companyName;
    data['profile_image'] = profileImage;
    return data;
  }
}

class NotificationsModelData {
/*
{
  "id": 11,
  "sender_id": 36,
  "receiver_id": 2,
  "type_id": null,
  "is_admin": 0,
  "title": null,
  "type": "Review",
  "message": "You received a rating from demouser11",
  "created_at": "2023-11-08T11:41:16.000000Z",
  "updated_at": "2023-11-08T11:41:16.000000Z",
  "user": {
    "id": 36,
    "full_name": "demouser11",
    "company_name": null,
    "profile_image": "profile_image/srd5iwWHMB3wTnCvICKewxve3hu4eKcqwP3kdD0I.jpg"
  }
}
*/

  int? id;
  int? senderId;
  int? receiverId;
  int? typeId;
  int? isAdmin;
  String? title;
  String? type;
  String? message;
  String? createdAt;
  String? updatedAt;
  NotificationsModelDataUser? user;

  NotificationsModelData({
    this.id,
    this.senderId,
    this.receiverId,
    this.typeId,
    this.isAdmin,
    this.title,
    this.type,
    this.message,
    this.createdAt,
    this.updatedAt,
    this.user,
  });
  NotificationsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    senderId = json['sender_id']?.toInt();
    receiverId = json['receiver_id']?.toInt();
    typeId = json['type_id']?.toInt();
    isAdmin = json['is_admin']?.toInt();
    title = json['title']?.toString();
    type = json['type']?.toString();
    message = json['message']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    user = (json['user'] != null) ? NotificationsModelDataUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sender_id'] = senderId;
    data['receiver_id'] = receiverId;
    data['type_id'] = typeId;
    data['is_admin'] = isAdmin;
    data['title'] = title;
    data['type'] = type;
    data['message'] = message;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}

class NotificationsModel {
/*
{
  "status": 1,
  "message": "Notifications",
  "data": [
    {
      "id": 11,
      "sender_id": 36,
      "receiver_id": 2,
      "type_id": null,
      "is_admin": 0,
      "title": null,
      "type": "Review",
      "message": "You received a rating from demouser11",
      "created_at": "2023-11-08T11:41:16.000000Z",
      "updated_at": "2023-11-08T11:41:16.000000Z",
      "user": {
        "id": 36,
        "full_name": "demouser11",
        "company_name": null,
        "profile_image": "profile_image/srd5iwWHMB3wTnCvICKewxve3hu4eKcqwP3kdD0I.jpg"
      }
    }
  ]
}
*/

  int? status;
  String? message;
  List<NotificationsModelData?>? data;

  NotificationsModel({
    this.status,
    this.message,
    this.data,
  });
  NotificationsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotificationsModelData>[];
      v.forEach((v) {
        arr0.add(NotificationsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}


// class NotificationsModelData {
// /*
// {
//   "id": 1,
//   "sender_id": 1,
//   "receiver_id": 2,
//   "service_id": null,
//   "is_admin": 0,
//   "type": "Review",
//   "message": "You received a rating from Demo Users",
//   "created_at": "2023-11-07T12:02:42.000000Z",
//   "updated_at": "2023-11-07T12:02:42.000000Z",
//   "user": null
// }
// */
//
//   int? id;
//   int? senderId;
//   int? receiverId;
//   String? serviceId;
//   int? isAdmin;
//   String? type;
//   String? message;
//   String? createdAt;
//   String? updatedAt;
//   String? user;
//
//   NotificationsModelData({
//     this.id,
//     this.senderId,
//     this.receiverId,
//     this.serviceId,
//     this.isAdmin,
//     this.type,
//     this.message,
//     this.createdAt,
//     this.updatedAt,
//     this.user,
//   });
//   NotificationsModelData.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     senderId = json['sender_id']?.toInt();
//     receiverId = json['receiver_id']?.toInt();
//     serviceId = json['service_id']?.toString();
//     isAdmin = json['is_admin']?.toInt();
//     type = json['type']?.toString();
//     message = json['message']?.toString();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     user = json['user']?.toString();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['sender_id'] = senderId;
//     data['receiver_id'] = receiverId;
//     data['service_id'] = serviceId;
//     data['is_admin'] = isAdmin;
//     data['type'] = type;
//     data['message'] = message;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['user'] = user;
//     return data;
//   }
// }
//
// class NotificationsModel {
// /*
// {
//   "status": 1,
//   "message": "Notifications",
//   "data": [
//     {
//       "id": 1,
//       "sender_id": 1,
//       "receiver_id": 2,
//       "service_id": null,
//       "is_admin": 0,
//       "type": "Review",
//       "message": "You received a rating from Demo Users",
//       "created_at": "2023-11-07T12:02:42.000000Z",
//       "updated_at": "2023-11-07T12:02:42.000000Z",
//       "user": null
//     }
//   ]
// }
// */
//
//   int? status;
//   String? message;
//   List<NotificationsModelData?>? data;
//
//   NotificationsModel({
//     this.status,
//     this.message,
//     this.data,
//   });
//   NotificationsModel.fromJson(Map<String, dynamic> json) {
//     status = json['status']?.toInt();
//     message = json['message']?.toString();
//     if (json['data'] != null) {
//       final v = json['data'];
//       final arr0 = <NotificationsModelData>[];
//       v.forEach((v) {
//         arr0.add(NotificationsModelData.fromJson(v));
//       });
//       this.data = arr0;
//     }
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['status'] = status;
//     data['message'] = message;
//     if (this.data != null) {
//       final v = this.data;
//       final arr0 = [];
//       v!.forEach((v) {
//         arr0.add(v!.toJson());
//       });
//       data['data'] = arr0;
//     }
//     return data;
//   }
// }
