///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PreferredNumbers {
/*
{
  "user_id": 9,
  "language": "a",
  "country_code": null,
  "phone_code": null,
  "phone_number": null
} 
*/

  int? userId;
  String? language;
  String? countryCode;
  String? phoneCode;
  String? phoneNumber;

  PreferredNumbers({
    this.userId,
    this.language,
    this.countryCode,
    this.phoneCode,
    this.phoneNumber,
  });
  PreferredNumbers.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    language = json['language']?.toString();
    countryCode = json['country_code']?.toString();
    phoneCode = json['phone_code']?.toString();
    phoneNumber = json['phone_number']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['language'] = language;
    data['country_code'] = countryCode;
    data['phone_code'] = phoneCode;
    data['phone_number'] = phoneNumber;
    return data;
  }
}

class PreferredLanguages {
/*
{
  "language_name": "a",
  "numbers": [
    {
      "user_id": 9,
      "language": "a",
      "country_code": null,
      "phone_code": null,
      "phone_number": null
    }
  ]
} 
*/

  String? languageName;
  List<PreferredNumbers>? numbers;

  PreferredLanguages({
    this.languageName,
    this.numbers,
  });
  PreferredLanguages.fromJson(Map<String, dynamic> json) {
    languageName = json['language_name']?.toString();
    if (json['numbers'] != null) {
      final v = json['numbers'];
      final arr0 = <PreferredNumbers>[];
      v.forEach((v) {
        arr0.add(PreferredNumbers.fromJson(v));
      });
      numbers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language_name'] = languageName;
    if (numbers != null) {
      final v = numbers;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['numbers'] = arr0;
    }
    return data;
  }
}

class User {
/*
{
  "id": 9,
  "otp": null,
  "role": "user",
  "full_name": "test",
  "email": "test6@gmail.com",
  "phone_number": "2233",
  "phone_code": "9",
  "country_code": "22",
  "address": "abc",
  "website": "abc",
  "profile_image": null,
  "company_name": "company",
  "card_id": null,
  "is_card": 0,
  "customer_id": null,
  "account_verified": 1,
  "email_verified_at": "2023-10-16T11:54:35.000000Z",
  "device_type": "IOS",
  "device_token": "123",
  "is_social": 0,
  "is_forgot": 0,
  "user_social_token": null,
  "user_social_type": null,
  "is_profile_complete": 0,
  "is_blocked": 0,
  "subscription_id": null,
  "api_token": "37|C2FNNr85CEJ46gKOex7pT1aVQ31YBbdveadyWQVOed8e8ef1",
  "notifications": 1,
  "deleted_at": null,
  "created_at": "2023-10-16T11:54:15.000000Z",
  "updated_at": "2023-10-17T06:28:58.000000Z",
  "languages": [
    {
      "language_name": "a",
      "numbers": [
        {
          "user_id": 9,
          "language": "a",
          "country_code": null,
          "phone_code": null,
          "phone_number": null
        }
      ]
    }
  ]
} 
*/

  int? id;
  String? otp;
  String? role;
  String? fullName;
  String? email;
  String? phoneNumber;
  String? phoneCode;
  String? countryCode;
  String? address;
  String? website;
  String? profileImage;
  String? companyName;
  String? companyDescription;
  String? cardId;
  int? isCard;
  String? customerId;
  int? accountVerified;
  String? emailVerifiedAt;
  String? deviceType;
  String? deviceToken;
  int? isSocial;
  int? isForgot;
  String? userSocialToken;
  String? userSocialType;
  int? isProfileComplete;
  int? isBlocked;
  String? subscriptionId;
  String? apiToken;
  int? notifications;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;
  List<PreferredLanguages>? languages;

  User({
    this.id,
    this.otp,
    this.role,
    this.fullName,
    this.email,
    this.phoneNumber,
    this.phoneCode,
    this.countryCode,
    this.address,
    this.website,
    this.profileImage,
    this.companyName,
    this.companyDescription,
    this.cardId,
    this.isCard,
    this.customerId,
    this.accountVerified,
    this.emailVerifiedAt,
    this.deviceType,
    this.deviceToken,
    this.isSocial,
    this.isForgot,
    this.userSocialToken,
    this.userSocialType,
    this.isProfileComplete,
    this.isBlocked,
    this.subscriptionId,
    this.apiToken,
    this.notifications,
    this.deletedAt,
    this.createdAt,
    this.updatedAt,
    this.languages,
  });
  User.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    otp = json['otp']?.toString();
    role = json['role']?.toString();
    fullName = json['full_name']?.toString();
    email = json['email']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneCode = json['phone_code']?.toString();
    countryCode = json['country_code']?.toString();
    address = json['address']?.toString();
    website = json['website']?.toString();
    profileImage = json['profile_image']?.toString();
    companyName = json['company_name']?.toString();
    companyDescription = json['company_description']?.toString();
    cardId = json['card_id']?.toString();
    isCard = json['is_card']?.toInt();
    customerId = json['customer_id']?.toString();
    accountVerified = json['account_verified']?.toInt();
    emailVerifiedAt = json['email_verified_at']?.toString();
    deviceType = json['device_type']?.toString();
    deviceToken = json['device_token']?.toString();
    isSocial = json['is_social']?.toInt();
    isForgot = json['is_forgot']?.toInt();
    userSocialToken = json['user_social_token']?.toString();
    userSocialType = json['user_social_type']?.toString();
    isProfileComplete = json['is_profile_complete']?.toInt();
    isBlocked = json['is_blocked']?.toInt();
    subscriptionId = json['subscription_id']?.toString();
    apiToken = json['api_token']?.toString();
    notifications = json['notifications']?.toInt();
    deletedAt = json['deleted_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    if (json['languages'] != null) {
      final v = json['languages'];
      final arr0 = <PreferredLanguages>[];
      v.forEach((v) {
        arr0.add(PreferredLanguages.fromJson(v));
      });
      languages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['otp'] = otp;
    data['role'] = role;
    data['full_name'] = fullName;
    data['email'] = email;
    data['phone_number'] = phoneNumber;
    data['phone_code'] = phoneCode;
    data['country_code'] = countryCode;
    data['address'] = address;
    data['website'] = website;
    data['profile_image'] = profileImage;
    data['company_name'] = companyName;
    data['company_description'] = companyDescription;
    data['card_id'] = cardId;
    data['is_card'] = isCard;
    data['customer_id'] = customerId;
    data['account_verified'] = accountVerified;
    data['email_verified_at'] = emailVerifiedAt;
    data['device_type'] = deviceType;
    data['device_token'] = deviceToken;
    data['is_social'] = isSocial;
    data['is_forgot'] = isForgot;
    data['user_social_token'] = userSocialToken;
    data['user_social_type'] = userSocialType;
    data['is_profile_complete'] = isProfileComplete;
    data['is_blocked'] = isBlocked;
    data['subscription_id'] = subscriptionId;
    data['api_token'] = apiToken;
    data['notifications'] = notifications;
    data['deleted_at'] = deletedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (languages != null) {
      final v = languages;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['languages'] = arr0;
    }
    return data;
  }
}

class UserResponseModel {
/*
{
  "status": 1,
  "message": "Profile completed successfully.",
  "data": {
    "id": 9,
    "otp": null,
    "role": "user",
    "full_name": "test",
    "email": "test6@gmail.com",
    "phone_number": "2233",
    "phone_code": "9",
    "country_code": "22",
    "address": "abc",
    "website": "abc",
    "profile_image": null,
    "company_name": "company",
    "card_id": null,
    "is_card": 0,
    "customer_id": null,
    "account_verified": 1,
    "email_verified_at": "2023-10-16T11:54:35.000000Z",
    "device_type": "IOS",
    "device_token": "123",
    "is_social": 0,
    "is_forgot": 0,
    "user_social_token": null,
    "user_social_type": null,
    "is_profile_complete": 0,
    "is_blocked": 0,
    "subscription_id": null,
    "api_token": "37|C2FNNr85CEJ46gKOex7pT1aVQ31YBbdveadyWQVOed8e8ef1",
    "notifications": 1,
    "deleted_at": null,
    "created_at": "2023-10-16T11:54:15.000000Z",
    "updated_at": "2023-10-17T06:28:58.000000Z",
    "languages": [
      {
        "language_name": "a",
        "numbers": [
          {
            "user_id": 9,
            "language": "a",
            "country_code": null,
            "phone_code": null,
            "phone_number": null
          }
        ]
      }
    ]
  }
} 
*/

  int? status;
  String? message;
  String? token;
  User? data;

  UserResponseModel({
    this.status,
    this.message,
    this.token,
    this.data,
  });
  UserResponseModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    token = json['token']?.toString();
    data = (json['data'] != null) ? User.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    data['token'] = token;
    if (data != null) {
      data['data'] = this.data?.toJson();
    }
    return data;
  }
}



// ///
// /// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
// ///
// class User {
// /*
// {
//   "id": 2,
//   "otp": 123456,
//   "role": "user",
//   "full_name": "test",
//   "email": "test@gmail.com",
//   "phone_number": "123456",
//   "phone_code": null,
//   "country_code": null,
//   "address": null,
//   "website": null,
//   "profile_image": null,
//   "company_name": null,
//   "card_id": null,
//   "is_card": 0,
//   "customer_id": null,
//   "account_verified": 1,
//   "email_verified_at": "2023-10-16T05:25:41.000000Z",
//   "device_type": null,
//   "device_token": null,
//   "is_social": 0,
//   "is_forgot": 0,
//   "user_social_token": null,
//   "user_social_type": null,
//   "is_profile_complete": null,
//   "is_blocked": 0,
//   "subscription_id": null,
//   "api_token": "1|4gyKdfMmYn7b1nWjtiaD2WJ1Xxn3HzZLAYq3wFAMad55318f",
//   "notifications": 1,
//   "deleted_at": null,
//   "created_at": "2023-10-16T05:22:15.000000Z",
//   "updated_at": "2023-10-16T05:25:41.000000Z",
//   "user_id": 2
// } 
// */

//   int? id;
//   int? otp;
//   String? role;
//   String? fullName;
//   String? email;
//   String? phoneNumber;
//   String? phoneCode;
//   String? countryCode;
//   String? address;
//   String? website;
//   String? profileImage;
//   String? companyName;
//   String? cardId;
//   int? isCard;
//   String? customerId;
//   int? accountVerified;
//   String? emailVerifiedAt;
//   String? deviceType;
//   String? deviceToken;
//   int? isSocial;
//   int? isForgot;
//   String? userSocialToken;
//   String? userSocialType;
//   String? isProfileComplete;
//   int? isBlocked;
//   String? subscriptionId;
//   String? apiToken;
//   int? notifications;
//   String? deletedAt;
//   String? createdAt;
//   String? updatedAt;
//   int? userId;

//   User({
//     this.id,
//     this.otp,
//     this.role,
//     this.fullName,
//     this.email,
//     this.phoneNumber,
//     this.phoneCode,
//     this.countryCode,
//     this.address,
//     this.website,
//     this.profileImage,
//     this.companyName,
//     this.cardId,
//     this.isCard,
//     this.customerId,
//     this.accountVerified,
//     this.emailVerifiedAt,
//     this.deviceType,
//     this.deviceToken,
//     this.isSocial,
//     this.isForgot,
//     this.userSocialToken,
//     this.userSocialType,
//     this.isProfileComplete,
//     this.isBlocked,
//     this.subscriptionId,
//     this.apiToken,
//     this.notifications,
//     this.deletedAt,
//     this.createdAt,
//     this.updatedAt,
//     this.userId,
//   });
//   User.fromJson(Map<String, dynamic> json) {
//     id = json['id']?.toInt();
//     otp = json['otp']?.toInt();
//     role = json['role']?.toString();
//     fullName = json['full_name']?.toString();
//     email = json['email']?.toString();
//     phoneNumber = json['phone_number']?.toString();
//     phoneCode = json['phone_code']?.toString();
//     countryCode = json['country_code']?.toString();
//     address = json['address']?.toString();
//     website = json['website']?.toString();
//     profileImage = json['profile_image']?.toString();
//     companyName = json['company_name']?.toString();
//     cardId = json['card_id']?.toString();
//     isCard = json['is_card']?.toInt();
//     customerId = json['customer_id']?.toString();
//     accountVerified = json['account_verified']?.toInt();
//     emailVerifiedAt = json['email_verified_at']?.toString();
//     deviceType = json['device_type']?.toString();
//     deviceToken = json['device_token']?.toString();
//     isSocial = json['is_social']?.toInt();
//     isForgot = json['is_forgot']?.toInt();
//     userSocialToken = json['user_social_token']?.toString();
//     userSocialType = json['user_social_type']?.toString();
//     isProfileComplete = json['is_profile_complete']?.toString();
//     isBlocked = json['is_blocked']?.toInt();
//     subscriptionId = json['subscription_id']?.toString();
//     apiToken = json['api_token']?.toString();
//     notifications = json['notifications']?.toInt();
//     deletedAt = json['deleted_at']?.toString();
//     createdAt = json['created_at']?.toString();
//     updatedAt = json['updated_at']?.toString();
//     userId = json['user_id']?.toInt();
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['otp'] = otp;
//     data['role'] = role;
//     data['full_name'] = fullName;
//     data['email'] = email;
//     data['phone_number'] = phoneNumber;
//     data['phone_code'] = phoneCode;
//     data['country_code'] = countryCode;
//     data['address'] = address;
//     data['website'] = website;
//     data['profile_image'] = profileImage;
//     data['company_name'] = companyName;
//     data['card_id'] = cardId;
//     data['is_card'] = isCard;
//     data['customer_id'] = customerId;
//     data['account_verified'] = accountVerified;
//     data['email_verified_at'] = emailVerifiedAt;
//     data['device_type'] = deviceType;
//     data['device_token'] = deviceToken;
//     data['is_social'] = isSocial;
//     data['is_forgot'] = isForgot;
//     data['user_social_token'] = userSocialToken;
//     data['user_social_type'] = userSocialType;
//     data['is_profile_complete'] = isProfileComplete;
//     data['is_blocked'] = isBlocked;
//     data['subscription_id'] = subscriptionId;
//     data['api_token'] = apiToken;
//     data['notifications'] = notifications;
//     data['deleted_at'] = deletedAt;
//     data['created_at'] = createdAt;
//     data['updated_at'] = updatedAt;
//     data['user_id'] = userId;
//     return data;
//   }
// }

// class UserResponseModel {
// /*
// {
//   "status": 1,
//   "message": "Account verified successfully",
//   "token": "1|4gyKdfMmYn7b1nWjtiaD2WJ1Xxn3HzZLAYq3wFAMad55318f",
//   "data": {
//     "id": 2,
//     "otp": 123456,
//     "role": "user",
//     "full_name": "test",
//     "email": "test@gmail.com",
//     "phone_number": "123456",
//     "phone_code": null,
//     "country_code": null,
//     "address": null,
//     "website": null,
//     "profile_image": null,
//     "company_name": null,
//     "card_id": null,
//     "is_card": 0,
//     "customer_id": null,
//     "account_verified": 1,
//     "email_verified_at": "2023-10-16T05:25:41.000000Z",
//     "device_type": null,
//     "device_token": null,
//     "is_social": 0,
//     "is_forgot": 0,
//     "user_social_token": null,
//     "user_social_type": null,
//     "is_profile_complete": null,
//     "is_blocked": 0,
//     "subscription_id": null,
//     "api_token": "1|4gyKdfMmYn7b1nWjtiaD2WJ1Xxn3HzZLAYq3wFAMad55318f",
//     "notifications": 1,
//     "deleted_at": null,
//     "created_at": "2023-10-16T05:22:15.000000Z",
//     "updated_at": "2023-10-16T05:25:41.000000Z",
//     "user_id": 2
//   }
// } 
// */

//   int? status;
//   String? message;
//   String? token;
//   User? data;

//   UserResponseModel({
//     this.status,
//     this.message,
//     this.token,
//     this.data,
//   });
//   UserResponseModel.fromJson(Map<String, dynamic> json) {
//     status = json['status']?.toInt();
//     message = json['message']?.toString();
//     token = json['token']?.toString();
//     data = (json['data'] != null) ? User.fromJson(json['data']) : null;
//   }
//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['status'] = status;
//     data['message'] = message;
//     data['token'] = token;
//     if (data != null) {
//       data['data'] = this.data?.toJson();
//     }
//     return data;
//   }
// }
